function force = force_of_infection(parsM, contact_vec_home, ...
    contact_vec_away, state_vec_home, state_vec_away)
Q_home = dot(contact_vec_home, state_vec_home(1:end-1));
Q_away = dot(contact_vec_away, state_vec_away(1:end-1));

row1 = parsM.etaI*contact_vec_home(1)*...
    (contact_vec_home(3)*state_vec_home(3) ...
    + contact_vec_away(3)*state_vec_away(3)*parsM.kappa)...
    /(Q_home + Q_away*parsM.kappa);

row2 = parsM.etaI*contact_vec_home(1)*parsM.kappa...
    *(contact_vec_home(3)*state_vec_home(3)*parsM.kappa ...
    + contact_vec_away(3)*state_vec_away(3))...
    /(Q_away + Q_home*parsM.kappa);

force = row1 + row2;
end